# Global AI Dataset Review

## Initial Data Inspection

This notebook performs the first review of the raw Global AI workplace dataset.

The goal of this step is to understand the structure of the raw data before cleaning, merging, feature engineering, or exploratory analysis.

The raw dataset is stored across five separate CSV files:

- `respondents.csv`
- `ai_tool_usage.csv`
- `salary_and_satisfaction.csv`
- `skills_and_training.csv`
- `ai_policy_and_ethics.csv`

In [1]:
# Import pandas for data loading and tabular data inspection

import pandas as pd

In [2]:
# Load all raw CSV files into separate DataFrames

respondents = pd.read_csv('../data/raw/respondents.csv')
usage = pd.read_csv('../data/raw/ai_tool_usage.csv')
salary = pd.read_csv('../data/raw/salary_and_satisfaction.csv')
skills = pd.read_csv('../data/raw/skills_and_training.csv')
ethics = pd.read_csv('../data/raw/ai_policy_and_ethics.csv')

## Respondents Table

In [3]:
# Inspect the structure of the respondents table

respondents.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   respondent_id        12000 non-null  str
 1   survey_year          12000 non-null  int64
 2   age                  12000 non-null  int64
 3   gender               12000 non-null  str
 4   country              12000 non-null  str
 5   education_level      12000 non-null  str
 6   job_role             12000 non-null  str
 7   industry             12000 non-null  str
 8   company_size         12000 non-null  str
 9   years_of_experience  12000 non-null  int64
 10  remote_work_status   12000 non-null  str
dtypes: int64(3), str(8)
memory usage: 1.0 MB

In [4]:
# Check available survey years

respondents["survey_year"].unique()

array([2025, 2024, 2026])

### Interpretation

The respondents table contains demographic and job-related information. The `survey_year` column is checked to understand the time period covered by the dataset.

## AI Tool Usage Table

In [5]:
# Inspect the structure of the AI tool usage table

usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 47206 entries, 0 to 47205
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   respondent_id            47206 non-null  str
 1   ai_tool                  47206 non-null  str
 2   usage_frequency          47206 non-null  str
 3   productivity_change_pct  47206 non-null  float64
 4   satisfaction_score       47206 non-null  int64
 5   primary_use_case         47206 non-null  str
dtypes: float64(1), int64(1), str(4)
memory usage: 2.2 MB

## Salary and Satisfaction Table

In [6]:
# Inspect the structure of the salary and satisfaction table

salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   respondent_id                  12000 non-null  str
 1   annual_salary_usd              12000 non-null  float64
 2   salary_change_yoy_pct          12000 non-null  float64
 3   job_satisfaction_score         12000 non-null  int64
 4   career_growth_outlook          12000 non-null  str
 5   ai_job_replacement_fear        12000 non-null  str
 6   job_search_status              12000 non-null  str
 7   received_ai_related_promotion  12000 non-null  str
 8   work_life_balance_score        12000 non-null  int64
 9   burnout_level                  9586 non-null   str
dtypes: float64(2), int64(2), str(6)
memory usage: 937.6 KB

## Skills and Training Table

In [7]:
# Inspect the structure of the skills and training table

skills.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   respondent_id                   12000 non-null  str
 1   skills                          12000 non-null  str
 2   num_skills                      12000 non-null  int64
 3   top_certification               8370 non-null   str
 4   weekly_learning_hours           12000 non-null  int64
 5   primary_learning_platform       12000 non-null  str
 6   learned_genai_skills_2024_2026  12000 non-null  str
 7   employer_provides_ai_training   12000 non-null  str
dtypes: int64(2), str(6)
memory usage: 750.1 KB

## AI Policy and Ethics Table

In [8]:
# Inspect the structure of the AI policy and ethics table

ethics.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   respondent_id               12000 non-null  str
 1   company_has_ai_policy       12000 non-null  str
 2   ai_bias_concern_level       12000 non-null  int64
 3   data_privacy_concern_level  12000 non-null  int64
 4   supports_ai_regulation      12000 non-null  str
 5   has_experienced_ai_misuse   12000 non-null  str
 6   trust_in_ai_decisions       12000 non-null  str
dtypes: int64(2), str(5)
memory usage: 656.4 KB

In [9]:
# Count unique values in each respondents column

respondents.nunique()

respondent_id          12000
survey_year                3
age                       43
gender                     4
country                   25
education_level            5
job_role                  15
industry                  15
company_size               6
years_of_experience       36
remote_work_status         3
dtype: int64

## Respondents Table

In [10]:
# Display number of rows, columns, and column names in respondents table

print("Shape:", respondents.shape)
print("Columns:", respondents.columns.tolist())

Shape: (12000, 11)
Columns: ['respondent_id', 'survey_year', 'age', 'gender', 'country', 'education_level', 'job_role', 'industry', 'company_size', 'years_of_experience', 'remote_work_status']

## AI Tool Usage Table

In [11]:
# Display number of rows, columns, and column names in AI tool usage table

print("Shape:", usage.shape)
print("Columns:", usage.columns.tolist())

Shape: (47206, 6)
Columns: ['respondent_id', 'ai_tool', 'usage_frequency', 'productivity_change_pct', 'satisfaction_score', 'primary_use_case']

## Salary and Satisfaction Table

In [12]:
# Display number of rows, columns, and column names in salary table

print("Shape:", salary.shape)
print("Columns:", salary.columns.tolist())

Shape: (12000, 10)
Columns: ['respondent_id', 'annual_salary_usd', 'salary_change_yoy_pct', 'job_satisfaction_score', 'career_growth_outlook', 'ai_job_replacement_fear', 'job_search_status', 'received_ai_related_promotion', 'work_life_balance_score', 'burnout_level']

## Skills and Training Table

In [13]:
# Display number of rows, columns, and column names in skills table

print("Shape:", skills.shape)
print("Columns:", skills.columns.tolist())

Shape: (12000, 8)
Columns: ['respondent_id', 'skills', 'num_skills', 'top_certification', 'weekly_learning_hours', 'primary_learning_platform', 'learned_genai_skills_2024_2026', 'employer_provides_ai_training']

## AI Policy and Ethics Table

In [14]:
# Display number of rows, columns, and column names in ethics table

print("Shape:", ethics.shape)
print("Columns:", ethics.columns.tolist())

Shape: (12000, 7)
Columns: ['respondent_id', 'company_has_ai_policy', 'ai_bias_concern_level', 'data_privacy_concern_level', 'supports_ai_regulation', 'has_experienced_ai_misuse', 'trust_in_ai_decisions']

In [15]:
# Check missing values in the respondents table

respondents.isna().sum()

respondent_id          0
survey_year            0
age                    0
gender                 0
country                0
education_level        0
job_role               0
industry               0
company_size           0
years_of_experience    0
remote_work_status     0
dtype: int64

In [16]:
# Check missing values in the AI tool usage table

usage.isna().sum()

respondent_id              0
ai_tool                    0
usage_frequency            0
productivity_change_pct    0
satisfaction_score         0
primary_use_case           0
dtype: int64

In [17]:
# Check missing values in the salary and satisfaction table

salary.isna().sum()

respondent_id                       0
annual_salary_usd                   0
salary_change_yoy_pct               0
job_satisfaction_score              0
career_growth_outlook               0
ai_job_replacement_fear             0
job_search_status                   0
received_ai_related_promotion       0
work_life_balance_score             0
burnout_level                    2414
dtype: int64

In [18]:
# Check missing values in the skills and training table

skills.isna().sum()

respondent_id                        0
skills                               0
num_skills                           0
top_certification                 3630
weekly_learning_hours                0
primary_learning_platform            0
learned_genai_skills_2024_2026       0
employer_provides_ai_training        0
dtype: int64

In [19]:
# Check missing values in the AI policy and ethics table

ethics.isna().sum()

respondent_id                 0
company_has_ai_policy         0
ai_bias_concern_level         0
data_privacy_concern_level    0
supports_ai_regulation        0
has_experienced_ai_misuse     0
trust_in_ai_decisions         0
dtype: int64

# Descriptive Statistics

Descriptive statistics are reviewed for numerical variables in the salary and skills tables.

This helps identify unusual ranges, potential outliers, and the general scale of the variables.

In [20]:
# Generate descriptive statistics for salary and satisfaction variables

salary.describe()

,annual_salary_usd,salary_change_yoy_pct,job_satisfaction_score,work_life_balance_score
count,12000.000000,12000.000000,12000.000000,12000.000000
mean,112710.466667,5.076842,3.631250,3.483667
std,75454.200547,8.103097,1.120213,1.123167
min,5000.000000,-25.000000,1.000000,1.000000
25%,50200.000000,-0.300000,3.000000,3.000000
50%,99600.000000,5.000000,4.000000,4.000000
75%,160700.000000,10.500000,4.000000,4.000000
max,566800.000000,36.800000,5.000000,5.000000

In [21]:
# Generate descriptive statistics for skills and training variables

skills.describe()

         num_skills  weekly_learning_hours
count  12000.000000           12000.000000
mean       8.041750               7.710583
std        2.767697               4.695582
min        3.000000               0.000000
25%        6.000000               4.000000
50%        8.000000               8.000000
75%       10.000000              11.000000
max       15.000000              30.000000

# Initial Categorical Distributions

A first look at categorical distributions helps understand the composition of the dataset.

In [22]:
# Count the most frequently used AI tools

usage["ai_tool"].value_counts()

ai_tool
Google Vertex AI            2448
Custom In-house AI          2418
Cursor                      2412
Stable Diffusion            2407
Jasper AI                   2403
Claude                      2394
Gemini                      2379
Notion AI                   2367
Replit AI                   2358
AWS Bedrock                 2357
Azure OpenAI                2354
ChatGPT                     2352
v0 by Vercel                2349
GitHub Copilot              2344
Perplexity                  2338
Hugging Face Models         2324
Tableau AI                  2322
Midjourney                  2317
LLaMA / Open-source LLMs    2284
Devin                       2279
Name: count, dtype: int64

In [23]:
# Count respondents by country

respondents["country"].value_counts()

country
United States     2154
India             1910
United Kingdom     922
Germany            863
Canada             708
Brazil             589
Japan              499
France             471
Australia          446
Singapore          384
Netherlands        361
South Korea        359
Nigeria            324
Mexico             250
UAE                245
Kenya              239
Poland             186
Sweden             184
South Africa       170
Indonesia          154
Spain              147
Israel             136
Italy              114
China              113
Philippines         72
Name: count, dtype: int64

In [24]:
# Count respondents by job role

respondents["job_role"].value_counts()

job_role
Data Scientist             1688
ML Engineer                1511
Software Engineer          1510
Data Analyst               1144
Full-Stack Developer        953
Product Manager             883
AI Researcher               733
Data Engineer               731
Business Analyst            706
DevOps / MLOps Engineer     567
UX Designer                 372
Engineering Manager         369
Student / Intern            339
AI Ethics / Policy          252
Consultant                  242
Name: count, dtype: int64

# Respondent ID Consistency

Before merging tables check whether `respondent_id` is present and consistent across all raw files.

In [25]:
# Compare the number of unique respondent IDs across all tables

print("respondents:", respondents["respondent_id"].nunique())
print("usage:", usage["respondent_id"].nunique())
print("salary:", salary["respondent_id"].nunique())
print("skills:", skills["respondent_id"].nunique())
print("ethics:", ethics["respondent_id"].nunique())

respondents: 12000
usage: 12000
salary: 12000
skills: 12000
ethics: 12000

In [26]:
# Check table size and respondent ID uniqueness for one-row-per-respondent tables

for name, table in {
    "respondents": respondents,
    "salary": salary,
    "skills": skills,
    "ethics": ethics
}.items():
    print(name, table.shape, table["respondent_id"].nunique())

respondents (12000, 11) 12000
salary (12000, 10) 12000
skills (12000, 8) 12000
ethics (12000, 7) 12000

# Review Summary

The initial dataset review showed that the raw data is organized across several related tables.

Main observations:

- `respondent_id` is the key variable for connecting the tables.
- Most tables appear to contain respondent-level information.
- The AI tool usage table requires special attention because it may contain multiple records per respondent.
- Missing values and categorical variables should be reviewed carefully during cleaning.
- The next step is to clean and merge the raw tables into a master dataset for EDA.

This notebook does not modify the data. Its purpose is to understand the raw structure before cleaning.