# AI Worker Burnout Dataset Cleaning

## Data Cleaning and Type Optimization

# 1. Import Libraries and Load Raw Data

In [1]:
# Import pandas for data cleaning and preprocessing

import pandas as pd

# Load the raw dataset

df = pd.read_csv("../data/raw/ai_worker_burnout_attrition_2026.csv")

# Display the first rows

df.head()

,employee_id,job_role,years_experience,education_level,country,industry,company_size,remote_work_type,team_size,salary_usd_k,...,ai_tools_used_per_day,hours_with_ai_assistance_daily,ai_replaces_my_tasks_pct,ai_adoption_stage,weekly_ai_upskilling_hrs,productivity_score,burnout_score,job_satisfaction_1_5,fear_of_ai_replacement,attrition_risk
0,EMP0001,Data Analyst,7,PhD,India,Healthtech,Large (1000-5000),Fully Remote,8,184,...,1,0.6,37,Experimenting,4.9,59,58,3.0,Low,Medium
1,EMP0002,DevOps Engineer,3,Self-taught,Canada,Fintech,Large (1000-5000),Hybrid,42,51,...,3,0.6,78,Experimenting,6.6,64,47,3.6,Medium,Medium
2,EMP0003,Prompt Engineer,3,PhD,India,Automotive,Startup (<50),Hybrid,37,185,...,4,4.0,23,Optimizing,5.8,50,37,4.6,High,Medium
3,EMP0004,Backend Engineer,18,Master,Germany,Media,Mid (200-1000),Fully Remote,8,131,...,5,4.2,75,Integrating,1.4,77,67,3.0,Low,Medium
4,EMP0005,AI Researcher,5,Bachelor,India,E-commerce,Small (50-200),Fully Remote,21,99,...,7,0.7,61,Experimenting,1.6,58,54,3.6,Medium,Medium

# 2. Initial Dataset Check

In [2]:
# Display dataset dimensions

df.shape

(1500, 21)

In [3]:
# Review column names, data types, and non-null values

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   employee_id                     1500 non-null   str
 1   job_role                        1500 non-null   str
 2   years_experience                1500 non-null   int64
 3   education_level                 1500 non-null   str
 4   country                         1500 non-null   str
 5   industry                        1500 non-null   str
 6   company_size                    1500 non-null   str
 7   remote_work_type                1500 non-null   str
 8   team_size                       1500 non-null   int64
 9   salary_usd_k                    1500 non-null   int64
 10  primary_ai_tool                 1500 non-null   str
 11  ai_tools_used_per_day           1500 non-null   int64
 12  hours_with_ai_assistance_daily  1500 non-null   float64
 13  ai_replaces_my_tasks_pct        1500 non-null   int64
 14  ai_adoption_stage               1500 non-null   str
 15  weekly_ai_upskilling_hrs        1500 non-null   float64
 16  productivity_score              1500 non-null   int64
 17  burnout_score                   1500 non-null   int64
 18  job_satisfaction_1_5            1500 non-null   float64
 19  fear_of_ai_replacement          1500 non-null   str
 20  attrition_risk                  1500 non-null   str
dtypes: float64(3), int64(7), str(11)
memory usage: 246.2 KB

In [4]:
# Check missing values before cleaning

df.isna().sum()

employee_id                       0
job_role                          0
years_experience                  0
education_level                   0
country                           0
industry                          0
company_size                      0
remote_work_type                  0
team_size                         0
salary_usd_k                      0
primary_ai_tool                   0
ai_tools_used_per_day             0
hours_with_ai_assistance_daily    0
ai_replaces_my_tasks_pct          0
ai_adoption_stage                 0
weekly_ai_upskilling_hrs          0
productivity_score                0
burnout_score                     0
job_satisfaction_1_5              0
fear_of_ai_replacement            0
attrition_risk                    0
dtype: int64

In [5]:
# Check duplicate rows before cleaning

df.duplicated().sum()

np.int64(0)

# 3. Memory Usage Before Optimization

In [6]:
# Calculate memory usage before type optimization

memory_before = df.memory_usage(deep=True).sum() / 1024

print(f"Memory before: {memory_before:.2f} KB")

Memory before: 1046.45 KB

# 4. Convert Object Columns to Category

Text-based columns with repeated values are converted from `object` to `category`.

In [7]:
# Convert object columns to category dtype

object_cols = df.select_dtypes(include="object").columns

for col in object_cols:
    df[col] = df[col].astype("category")

object_cols

/var/folders/_d/9zcx7q8s1yb7ztxbxc0bg95w0000gn/T/ipykernel_44711/1163080292.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include="object").columns

Index(['employee_id', 'job_role', 'education_level', 'country', 'industry',
       'company_size', 'remote_work_type', 'primary_ai_tool',
       'ai_adoption_stage', 'fear_of_ai_replacement', 'attrition_risk'],
      dtype='str')

# 5. Downcast Integer Columns

Integer columns are downcast to smaller integer types where possible.

This reduces memory usage while keeping the same numerical information.

In [8]:
# Downcast integer columns to reduce memory usage

int_cols = df.select_dtypes(include="int64").columns

for col in int_cols:
    df[col] = pd.to_numeric(df[col], downcast="integer")

int_cols

Index(['years_experience', 'team_size', 'salary_usd_k',
       'ai_tools_used_per_day', 'ai_replaces_my_tasks_pct',
       'productivity_score', 'burnout_score'],
      dtype='str')

# 6. Downcast Float Columns

Float columns are downcast to smaller float types where possible.

This helps reduce memory usage while preserving the values needed for analysis.

In [9]:
# Downcast float columns to reduce memory usage

float_cols = df.select_dtypes(include="float64").columns

for col in float_cols:
    df[col] = pd.to_numeric(df[col], downcast="float")

float_cols

Index(['hours_with_ai_assistance_daily', 'weekly_ai_upskilling_hrs',
       'job_satisfaction_1_5'],
      dtype='str')

# 7. Memory Usage After Optimization

The memory usage is calculated again after type conversion.

This shows how much memory was saved through data type optimization.

In [10]:
# Calculate memory usage after type optimization

memory_after = df.memory_usage(deep=True).sum() / 1024

print(f"Memory after: {memory_after:.2f} KB")
print(f"Reduction: {(1 - memory_after / memory_before) * 100:.2f}%")

Memory after: 132.63 KB
Reduction: 87.33%

# 8. Final Quality Check

In [11]:
# Review final dataset structure after cleaning

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   employee_id                     1500 non-null   category
 1   job_role                        1500 non-null   category
 2   years_experience                1500 non-null   int8
 3   education_level                 1500 non-null   category
 4   country                         1500 non-null   category
 5   industry                        1500 non-null   category
 6   company_size                    1500 non-null   category
 7   remote_work_type                1500 non-null   category
 8   team_size                       1500 non-null   int8
 9   salary_usd_k                    1500 non-null   int16
 10  primary_ai_tool                 1500 non-null   category
 11  ai_tools_used_per_day           1500 non-null   int8
 12  hours_with_ai_assistance_daily  1500 non-null   float32
 13  ai_replaces_my_tasks_pct        1500 non-null   int8
 14  ai_adoption_stage               1500 non-null   category
 15  weekly_ai_upskilling_hrs        1500 non-null   float32
 16  productivity_score              1500 non-null   int8
 17  burnout_score                   1500 non-null   int8
 18  job_satisfaction_1_5            1500 non-null   float32
 19  fear_of_ai_replacement          1500 non-null   category
 20  attrition_risk                  1500 non-null   category
dtypes: category(11), float32(3), int16(1), int8(6)
memory usage: 59.5 KB

In [12]:
# Check missing values after cleaning

df.isna().sum()

employee_id                       0
job_role                          0
years_experience                  0
education_level                   0
country                           0
industry                          0
company_size                      0
remote_work_type                  0
team_size                         0
salary_usd_k                      0
primary_ai_tool                   0
ai_tools_used_per_day             0
hours_with_ai_assistance_daily    0
ai_replaces_my_tasks_pct          0
ai_adoption_stage                 0
weekly_ai_upskilling_hrs          0
productivity_score                0
burnout_score                     0
job_satisfaction_1_5              0
fear_of_ai_replacement            0
attrition_risk                    0
dtype: int64

In [13]:
# Check duplicate rows after cleaning

df.duplicated().sum()

np.int64(0)

In [14]:
# Preview the cleaned dataset

df.head()

,employee_id,job_role,years_experience,education_level,country,industry,company_size,remote_work_type,team_size,salary_usd_k,...,ai_tools_used_per_day,hours_with_ai_assistance_daily,ai_replaces_my_tasks_pct,ai_adoption_stage,weekly_ai_upskilling_hrs,productivity_score,burnout_score,job_satisfaction_1_5,fear_of_ai_replacement,attrition_risk
0,EMP0001,Data Analyst,7,PhD,India,Healthtech,Large (1000-5000),Fully Remote,8,184,...,1,0.6,37,Experimenting,4.9,59,58,3.0,Low,Medium
1,EMP0002,DevOps Engineer,3,Self-taught,Canada,Fintech,Large (1000-5000),Hybrid,42,51,...,3,0.6,78,Experimenting,6.6,64,47,3.6,Medium,Medium
2,EMP0003,Prompt Engineer,3,PhD,India,Automotive,Startup (<50),Hybrid,37,185,...,4,4.0,23,Optimizing,5.8,50,37,4.6,High,Medium
3,EMP0004,Backend Engineer,18,Master,Germany,Media,Mid (200-1000),Fully Remote,8,131,...,5,4.2,75,Integrating,1.4,77,67,3.0,Low,Medium
4,EMP0005,AI Researcher,5,Bachelor,India,E-commerce,Small (50-200),Fully Remote,21,99,...,7,0.7,61,Experimenting,1.6,58,54,3.6,Medium,Medium

# 9. Export Cleaned Dataset

The cleaned dataset is exported to the `data/processed` folder.

In [15]:
# Export cleaned dataset to processed data folder

df.to_csv(
    "../data/processed/ai_worker_burnout_cleaned.csv",
    index=False
)

# Cleaning Summary

The data cleaning process included:

- loading the raw AI worker burnout dataset,
- checking dataset dimensions, missing values, and duplicates,
- converting categorical text columns to `category`,
- downcasting integer and float columns,
- reducing memory usage,
- verifying the final dataset structure,
- exporting the cleaned dataset.

No analytical conclusions are drawn in this notebook. The purpose is to prepare a clean and efficient dataset for the following EDA and modeling notebooks.